```{r}
trainingDataRaw <- read.csv(url("https://raw.githubusercontent.com/dsmilo/DATA621/master/moneyball-training-data.csv")) #Load the training data
#Create a linear model using all predictors. The INDEX column is excluded.
FullModel <- lm(TARGET_WINS ~.-INDEX, trainingDataRaw)
summary(FullModel) #Summary of full model
#Put full model through stepwise regression, where predictors with less significance are sequentially removed.
stepFull <- step(FullModel) 
summary(stepFull)


#Generate predictions using the stepFull model
predictionsStepFull <- predict(stepFull, trainingDataRaw) 
View(predictionsStepFull)

#Generate the RMSE of the stepFull model
rmseStep <- sqrt(mean((trainingDataRaw$TARGET_WINS[!is.na(predictionsStepFull)] - predictionsStepFull[!is.na(predictionsStepFull)])^2)) 
rmseStep

 #Set up a four panel plot for evaluating regression
par(mfrow=c(2,2))
#Displays Residuals vs Fitted, Scale-Location,  and Normal Q-Q.
plot(stepFull) 

```

```{r}
#Evaluation of Stepwise model without TEAM_BATTING_HBP
ReducedModel <- lm(TARGET_WINS ~., trainingDataRaw[,c(2:10, 12:17)])
summary(ReducedModel)
stepReduced <- step(ReducedModel)
predictionsStepReduced <- predict(stepReduced, trainingDataRaw[,c(2:10, 12:17)])
rmseStepR <- sqrt(mean((trainingDataRaw$TARGET_WINS[!is.na(predictionsStepReduced)] - predictionsStepReduced[!is.na(predictionsStepReduced)])^2))
rmseStepR
```
